version: '2'
services:
  eureka:
    build: ./annuaire-eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - "discovery"
    environment:
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
networks:
  discovery: