version: '2'
services:
  eureka:
    build: ./annuaire-eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - "discovery"
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - "eureka"
    links:
      - "eureka"
    ports:
      - "80:80"
    networks:
      - "discovery"
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_STATUS_PAGE_URL=http://192.168.2.23:80/actuator/info
  commande:
    build: ./commande
    container_name: commande
    depends_on:
      - "eureka"
      - "gateway"
    links:
      - "eureka"
    ports:
      - "8081:8080"
    networks:
      - "discovery"
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_STATUS_PAGE_URL=http://192.168.2.23:8081/actuator/info
networks:
  discovery: