version: '2'
services:
  eureka:
    build: ./annuaire-eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - "discovery"
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - "eureka"
    links:
      - "eureka"
    ports:
      - "80:80"
    networks:
      - "discovery"
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
networks:
  discovery: